# This is a basic workflow to help you get started with Actions

name: frontend-develop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Docker login (by kimhaechang)
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Build
        run: docker build --platform linux/arm64/v8 -t frontend .
      
      # Runs a set of commands using the runners shell
      - name: Docker image push
        run: |
          docker tag frontend ${{ secrets.DOCKER_USERNAME }}/tk-client
          docker push ${{ secrets.DOCKER_USERNAME }}/tk-client
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: github_action
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker rm -f tkbus_frontend_1 || true
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/tk-client
            docker-compose -f ${{ vars.FRONTEND_DOCKER_COMPOSE_PATH }} up -d
